# Generated by Django 5.2.17 on 2026-10-06 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Código del selector: carrera, salto, patear…', max_length=30, unique=True)),
                ('nombre', models.CharField(help_text='Nombre canónico usado por el motor', max_length=60, unique=True)),
                ('componente', models.CharField(choices=[('HMB-L', 'Locomoción'), ('HMB-M', 'Manipulación'), ('HMB-E', 'Estabilidad-Equilibrio')], max_length=5)),
                ('prueba_nro', models.PositiveSmallIntegerField(verbose_name='prueba n.º en la batería')),
                ('protocolo', models.TextField()),
                ('icono', models.CharField(blank=True, max_length=8)),
                ('frases_profe', models.JSONField(default=list, verbose_name='frases del profe')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'habilidad',
                'verbose_name_plural': 'habilidades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CriterioHMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('texto', models.TextField()),
                ('fase', models.CharField(max_length=40)),
                ('umbral_texto', models.CharField(max_length=120, verbose_name='umbral mostrado')),
                ('error_titulo', models.CharField(max_length=200, verbose_name='error si no se logra')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='catalogo.habilidad')),
            ],
            options={
                'verbose_name': 'criterio HMB',
                'verbose_name_plural': 'criterios HMB',
                'ordering': ['habilidad__orden', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('habilidad', 'orden'), name='criterio_unico_por_habilidad')],
            },
        ),
        migrations.CreateModel(
            name='PlantillaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('fase_pedagogica', models.CharField(max_length=80)),
                ('objetivo', models.TextField()),
                ('distribucion', models.TextField()),
                ('actividad_inicial', models.TextField()),
                ('actividad_central', models.TextField()),
                ('actividad_final', models.TextField()),
                ('consigna', models.TextField()),
                ('criterio_eval', models.TextField(verbose_name='criterio de evaluación')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='catalogo.habilidad')),
            ],
            options={
                'verbose_name': 'plantilla de sesión',
                'verbose_name_plural': 'plantillas de sesión',
                'ordering': ['habilidad__orden', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('habilidad', 'orden'), name='plantilla_unica_por_habilidad')],
            },
        ),
    ]
