# Generated by Django 5.2.17 on 2026-10-06 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('grado', models.CharField(choices=[('5_anos', 'Transición / Preescolar (5 años)'), ('6_anos', 'Grado 1º de Primaria (6 años)'), ('7_anos', 'Grado 2º de Primaria (7 años)'), ('8_anos', 'Grado 3º de Primaria (8 años)'), ('9_11_anos', 'Grado 4º - 5º (9 a 11 años)')], max_length=12)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='cuentas.institucion')),
            ],
            options={
                'ordering': ['-anio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(blank=True, max_length=120)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('acudiente', models.CharField(blank=True, max_length=150)),
                ('consentimiento_video', models.BooleanField(default=False, verbose_name='autoriza grabar y analizar video')),
                ('consentimiento_ia_nube', models.BooleanField(default=False, verbose_name='autoriza enviar fotogramas a IA en la nube')),
                ('fecha_consentimiento', models.DateField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='estudiantes.grupo')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('institucion', 'nombre', 'anio'), name='grupo_unico_por_anio'),
        ),
    ]
