# Generated by Django 5.2.17 on 2026-10-06 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadDidactica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('Cuento Motor', 'Cuento Motor'), ('Circuito de Estaciones', 'Circuito'), ('Retos Cooperativos', 'Retos'), ('Juego Libre Dirigido', 'Juego Libre')], default='Circuito de Estaciones', max_length=40)),
                ('metodologia', models.CharField(choices=[('Descubrimiento Guiado', 'Descubrimiento'), ('Resolución de Problemas', 'Problemas'), ('Asignación de Tareas', 'Tareas')], default='Asignación de Tareas', max_length=40)),
                ('materiales', models.JSONField(default=list)),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Período 1'), (2, 'Período 2'), (3, 'Período 3'), (4, 'Período 4')], default=1)),
                ('duracion_min', models.PositiveSmallIntegerField(choices=[(45, '45 min'), (50, '50 min'), (55, '55 min'), (60, '60 min'), (90, '90 min')], default=50)),
                ('total_clases', models.PositiveSmallIntegerField(choices=[(1, '1 clase'), (2, '2 clases'), (3, '3 clases'), (4, '4 clases'), (6, '6 clases'), (8, '8 clases'), (10, '10 clases'), (12, '12 clases')], default=12)),
                ('contenido', models.JSONField(blank=True, default=dict, help_text='Objeto UnidadDidactica completo (docs/04 §2.5)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='evaluaciones.evaluacion')),
                ('evaluacion_grupal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='evaluaciones.evaluaciongrupal')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.habilidad')),
            ],
            options={
                'verbose_name': 'unidad didáctica',
                'verbose_name_plural': 'unidades didácticas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('es_refuerzo', models.BooleanField(default=False)),
                ('error_reforzado', models.CharField(blank=True, max_length=200)),
                ('titulo', models.CharField(max_length=220)),
                ('fase_pedagogica', models.CharField(blank=True, max_length=80)),
                ('objetivo', models.TextField()),
                ('distribucion', models.TextField(blank=True)),
                ('actividad_inicial', models.TextField()),
                ('actividad_central', models.TextField()),
                ('actividad_final', models.TextField()),
                ('consigna', models.TextField(blank=True)),
                ('criterio_eval', models.TextField(blank=True)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.plantillasesion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='planeacion.unidaddidactica')),
            ],
            options={
                'verbose_name': 'sesión',
                'verbose_name_plural': 'sesiones',
                'ordering': ['unidad', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('unidad', 'numero'), name='sesion_unica_por_numero')],
            },
        ),
    ]
