# Generated by Django 5.2.17 on 2026-10-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidaddidactica',
            name='formato',
            field=models.CharField(choices=[('Cuento Motor', 'Cuento Motor'), ('Circuito de Estaciones', 'Circuito de Estaciones'), ('Retos Cooperativos', 'Retos Cooperativos'), ('Juego Libre Dirigido', 'Juego Libre Dirigido')], default='Circuito de Estaciones', max_length=40),
        ),
        migrations.AlterField(
            model_name='unidaddidactica',
            name='metodologia',
            field=models.CharField(choices=[('Descubrimiento Guiado', 'Descubrimiento Guiado'), ('Resolución de Problemas', 'Resolución de Problemas'), ('Asignación de Tareas', 'Asignación de Tareas')], default='Asignación de Tareas', max_length=40),
        ),
    ]
