# Generated by Django 5.2.17 on 2026-10-06 02:43

import apps.evaluaciones.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiantes_objetivo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_grupales', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_grupales', to='estudiantes.grupo')),
                ('habilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.habilidad')),
            ],
            options={
                'verbose_name': 'evaluación grupal',
                'verbose_name_plural': 'evaluaciones grupales',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, storage=apps.evaluaciones.models.almacenamiento_privado, upload_to='evidencias/%Y/%m/')),
                ('tipo_archivo', models.CharField(blank=True, choices=[('video', 'Video'), ('imagen', 'Imagen')], max_length=10)),
                ('grado', models.CharField(choices=[('5_anos', 'Transición / Preescolar (5 años)'), ('6_anos', 'Grado 1º de Primaria (6 años)'), ('7_anos', 'Grado 2º de Primaria (7 años)'), ('8_anos', 'Grado 3º de Primaria (8 años)'), ('9_11_anos', 'Grado 4º - 5º (9 a 11 años)')], default='7_anos', max_length=12)),
                ('observaciones_docente', models.TextField(blank=True)),
                ('motor', models.CharField(choices=[('local', 'Local (reglas)'), ('gemini', 'Gemini Vision')], default='local', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('lista', 'Lista'), ('error', 'Error')], default='pendiente', max_length=12)),
                ('mensaje_error', models.TextField(blank=True)),
                ('es_deteccion_automatica', models.BooleanField(default=False)),
                ('puntaje', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('puntaje_maximo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('porcentaje_madurez', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estadio_gallahue', models.CharField(blank=True, choices=[('Inicial', 'Inicial'), ('Elemental', 'Elemental'), ('Maduro', 'Maduro')], max_length=10)),
                ('resumen', models.TextField(blank=True)),
                ('analisis_articular', models.JSONField(blank=True, default=dict)),
                ('errores_criticos', models.JSONField(blank=True, default=list)),
                ('frases_profe', models.JSONField(blank=True, default=list)),
                ('telemetria', models.JSONField(blank=True, default=dict)),
                ('fases_fsm', models.JSONField(blank=True, default=list)),
                ('modelo_ia', models.CharField(blank=True, max_length=60)),
                ('version_motor', models.CharField(blank=True, help_text='Para reproducir el resultado si cambian los umbrales', max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='estudiantes.estudiante')),
                ('habilidad_detectada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.habilidad')),
                ('habilidad_solicitada', models.ForeignKey(blank=True, help_text='Vacío = detección automática', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.habilidad')),
                ('evaluacion_grupal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='evaluaciones.evaluaciongrupal')),
            ],
            options={
                'verbose_name': 'evaluación',
                'verbose_name_plural': 'evaluaciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Fotograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('tiempo_s', models.FloatField()),
                ('fase', models.CharField(blank=True, max_length=120)),
                ('imagen', models.ImageField(blank=True, storage=apps.evaluaciones.models.almacenamiento_privado, upload_to='fotogramas/')),
                ('imagen_esqueleto', models.ImageField(blank=True, storage=apps.evaluaciones.models.almacenamiento_privado, upload_to='fotogramas/')),
                ('landmarks', models.JSONField(blank=True, null=True)),
                ('angulos', models.JSONField(blank=True, null=True)),
                ('es_gatillo', models.BooleanField(default=False)),
                ('hito_tipo', models.CharField(blank=True, choices=[('', '—'), ('inicial', 'Ángulo inicial'), ('pico', 'Pico del gesto'), ('sub', 'Hito secundario'), ('final', 'Cierre')], max_length=10)),
                ('hito_badge', models.CharField(blank=True, max_length=60)),
                ('hito_titulo', models.CharField(blank=True, max_length=120)),
                ('hito_desc', models.CharField(blank=True, max_length=200)),
                ('hito_color', models.CharField(blank=True, max_length=9)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotogramas', to='evaluaciones.evaluacion')),
            ],
            options={
                'ordering': ['evaluacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('texto', models.TextField()),
                ('fase', models.CharField(blank=True, max_length=40)),
                ('puntaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('medido', models.CharField(blank=True, max_length=200)),
                ('umbral', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('criterio', models.ForeignKey(blank=True, help_text='Vacío si el criterio vino como texto libre de la IA', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.criteriohmb')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluaciones.evaluacion')),
            ],
            options={
                'verbose_name': 'resultado de criterio',
                'verbose_name_plural': 'resultados de criterios',
                'ordering': ['evaluacion', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['estudiante', '-creado'], name='evaluacione_estudia_fe88e1_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['estado'], name='evaluacione_estado_e0ab09_idx'),
        ),
        migrations.AddConstraint(
            model_name='fotograma',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'orden'), name='fotograma_unico_por_orden'),
        ),
    ]
