# Generated by Django 5.2.17 on 2026-10-06 03:30

import apps.evaluaciones.models
import apps.evaluaciones.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='archivo_purgado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se borró el video por retención', null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='archivo',
            field=models.FileField(blank=True, storage=apps.evaluaciones.models.almacenamiento_privado, upload_to='evidencias/%Y/%m/', validators=[apps.evaluaciones.validadores.validar_evidencia]),
        ),
    ]
