# Generated by Django 5.2.17 on 2026-10-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_validacion_y_retencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='advertencias',
            field=models.JSONField(blank=True, default=list, help_text='Avisos de calidad de la grabación para el docente'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='meta_video',
            field=models.JSONField(blank=True, default=dict, help_text='Resolución, fps, duración y ventana analizada'),
        ),
    ]
